### ISSUE TITLE
Could I do a code review?

### ISSUE THREAD

**Issue by mattfbacon** [angelina-tsuboi/ctv#3]
Hi,

I'm not sure if you remember me but we were in the same team at that AI camp about a year ago.

I'm glad you're interested in Rust! It's been my language of choice for a couple of months now. Reading through the code, I see some things I could fix. Would you be interested?

If you'd like to see some of the code I've written in Rust, here's an example: https://github.com/V5Reveng/cli

**Comment by angelina-tsuboi** [comment]
@mattfbacon Of course, I remember you! It was a lot of fun making the Fake News Detector with you.
I would really appreciate it if you could do a code review. I am fairly new to Rust, so it would be great to have you look over the code. Thanks!

**Comment by mattfbacon** [comment]
One thing I'm wondering: if I make it so that all the config variables can be set via the environment, do you still want them to be able to be set from the command line arguments?

**Comment by angelina-tsuboi** [comment]
If you're able to make it so the config variables can be set via the environment, I don't think we would need to be able to set the config variables via command line arguments. Feel free to make the functionality and remove the set-var command line feature. Just make sure to update the READMe once you're done. Thanks!
